# Generated by Django 4.1.7 on 2023-03-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelogo',
            options={'verbose_name_plural': 'Site Logo'},
        ),
        migrations.RenameField(
            model_name='sitelogo',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='productImg'),
        ),
    ]
