# Generated by Django 4.1.7 on 2023-03-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_sitelogo_options_rename_name_sitelogo_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Category'},
        ),
    ]
