# Generated by Django 4.1.7 on 2023-03-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(default='https://th.bing.com/th/id/OIP.oWPLGwKQFynuDWH43wlwgAHaLH?w=215&h=322&c=7&o=5&pid=1.7', upload_to='hoverProductImage'),
        ),
    ]
